"""Add is_infected to File

Revision ID: 68fe86ed684a
Revises: 1146b3fe0fd0
Create Date: 2025-04-30 10:45:04.774333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fe86ed684a'
down_revision: Union[str, None] = '1146b3fe0fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем лишние create_unique_constraint, если они не нужны или уже существуют
    # op.create_unique_constraint(None, 'file_encryption', ['id']) # Скорее всего, лишнее
    # Добавляем server_default='false'
    op.add_column('files', sa.Column('is_infected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # op.create_unique_constraint(None, 'files', ['id']) # Скорее всего, лишнее
    # op.create_unique_constraint(None, 'password_reset_tokens', ['id']) # Скорее всего, лишнее
    # op.create_unique_constraint(None, 'user_activity_logs', ['id']) # Скорее всего, лишнее
    # op.create_unique_constraint(None, 'user_sessions', ['id']) # Скорее всего, лишнее
    # op.create_unique_constraint(None, 'user_settings', ['id']) # Скорее всего, лишнее
    # op.create_unique_constraint(None, 'users', ['id']) # Скорее всего, лишнее
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique') # Скорее всего, лишнее
    # op.drop_constraint(None, 'user_settings', type_='unique') # Скорее всего, лишнее
    # op.drop_constraint(None, 'user_sessions', type_='unique') # Скорее всего, лишнее
    # op.drop_constraint(None, 'user_activity_logs', type_='unique') # Скорее всего, лишнее
    # op.drop_constraint(None, 'password_reset_tokens', type_='unique') # Скорее всего, лишнее
    # op.drop_constraint(None, 'files', type_='unique') # Скорее всего, лишнее
    op.drop_column('files', 'is_infected')
    # op.drop_constraint(None, 'file_encryption', type_='unique') # Скорее всего, лишнее
    # ### end Alembic commands ###
